# Generated by Django 5.0.6 on 2024-05-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='SignedDocument',
        ),
    ]
